// larger program
print( 3 );
print( 3.2 );
print( "foobar" );
print( 3 + 2 );
print( 3.2 + 5.1 );
print( 3 + 4 * 7 );
Integer x = 5;
print( x );
String y = "foobar";
print( y );
print( -5 );
print( -3.2 );
print( -5 - 2 );
print( 5 - -2 * 3 );
print( 5 / 2 );
print( 5 + 2 ^ 4 );
print( x + 2 );
print( x + 6 );
print( concat( "foo", "bar" ) );
print( charAt( "foobar", 0 ) );
print( charAt( y, 0 ) );
print( concat( y, "baz" ) );
print( x + x );